name: build-and-publish
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/myscorelinux-server:latest

    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Publish Docker Image
      run: docker push ${{secrets.DOCKER_USER}}/myscorelinux-server:latest
